app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from. import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(20),index = True, unique=True,nullable = False)
    pass_secure = db.Column(db.String(120),nullable = False)
    email = db.Column(db.String(120),unique = True,index = True)
    ideas = db.relationship('Idea',backref = 'owner',lazy='dynamic')
    profile_pic = db.Column(db.String(20),nullable = False,default = 'default.jpg')

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)


    def __repr__(self):
        return f'User ("{self.username}","{self.profile_pic}")'

class Idea(db.Model):
    __tablename__ = 'idea'

    id = db.Column(db.Integer,primary_key = True)
    title = db.Column(db.String(100),nullable = False)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    body = db.Column(db.Text)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'),nullable = False)
    
    

    @classmethod
    def get_ideas(cls,id):
        ideas = Idea.query.filter_by(id=id).all()
        return ideas


    def __repr__(self):
        return f'User ("{self.title}","{self.body}")'

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()


def create_app(config_name):

    app = Flask(__name__)
    

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    # Will add the views and forms

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views,errors

app/main/views.py
from flask import Flask, render_template,request,redirect,url_for,abort
from ..models import Idea,User
from flask_login import login_required,current_user
from flask_bootstrap import Bootstrap
from flask_wtf import FlaskForm
from . import main
from .form import IdeaForm
from .. import db

@main.route('/')
def index():

    '''
    View root page function that returns the index page and its data
    '''

    

    return render_template('index.html')

@main.route('/user/<uname>', methods = ['GET','POST'])
@login_required
def profile(uname):

    form = IdeaForm()
    user = User.query.filter_by(username = uname).first()
    ideas = Idea.query.all()
    if form.validate_on_submit():
        title = form.title.data
        body = form.body.data

        
        new_idea = Idea(title=form.title.data,body=form.body.data,owner = current_user)
        
        db.session.add(new_idea)
        db.session.commit()
                            
    

    return render_template("profile/profile.html",ideas = ideas, user = user,idea_form = form)


    

app/templates/base.html
{% extends 'bootstrap/base.html'%}
{%block styles%}
<!-- Font Awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
<!-- Bootstrap core CSS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
<!-- Material Design Bootstrap -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.10.1/css/mdb.min.css" rel="stylesheet">
<link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}">
{%endblock%}

{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html'%}

{% block content %}
    <h1>WHOOOPS we can't find that page</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container landing">
  <div class="row">
    <div class="col-md-12">
      
      <h1>Welcome</h1>
      <h6>What briliant ideas do you have?
      </h6>
      <button class="btn peach-gradient" >Make
        Pitch</button>
      
    </div>
  </div>
</div>


{% endblock %}

app/templates/navbar.html
<nav class="mb-1 navbar navbar-expand-lg navbar-dark orange lighten-1">
  <a class="navbar-brand" href="#">Pitches</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-555"
    aria-controls="navbarSupportedContent-555" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent-555">
    <ul class="navbar-nav mr-auto">
      {% if current_user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('auth.logout')}}">Log out</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('auth.login')}}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('auth.signup')}}">Signup</a>
      </li>
      {%endif%}
    </ul>

    <ul class="navbar-nav ml-auto nav-flex-icons">
    </ul>
  </div>
</nav>

app/templates/profile/profile.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}

<div class="container">
  <div class="row">
    <div class="profile col-md-4">
      <h3> {{user.username| capitalize}} </h3>
      {% if user.profile_pic %}
      <img src="{{url_for('static',filename=user.profile_pic)}}" alt="" class="img-thumbnail">
      {%else%}
      <p>No profile picture</p>
      {% endif %}
    </div>
    <div class="pitches col-md-8">
      {{wtf.quick_form(idea_form)}}
      {% for idea in ideas %}
      <div class="card">
        <h1>{{idea.title}}</h1>
        <p>{{idea.body}}</p>
      </div>
      {%endfor%}
    </div>
  </div>
</div>
{% endblock %}